import { createSlice } from '@reduxjs/toolkit';

// `createSlice` is a function from Redux Toolkit that simplifies the process of creating Redux slices.
// A slice is a portion of the Redux state that is managed by a specific reducer.

const userSlice = createSlice({
  name: 'users', // The name of the slice, used as a prefix for the action types.
  
  initialState: {
    selectedUser: null, // Initial state of the slice, with `selectedUser` set to null.
  },
  
  reducers: {
    // Reducers are functions that handle actions and modify the state.

    selectUser: (state, action) => {
      // Action to select a user. 
      // It receives the current state and an action object with the payload.
      state.selectedUser = action.payload; // Update `selectedUser` with the payload (the user object).
    },

    clearSelectedUser: (state) => {
      // Action to clear the selected user.
      state.selectedUser = null; // Reset `selectedUser` back to null.
    },
  },
});

// Export the action creators generated by createSlice.
export const { selectUser, clearSelectedUser } = userSlice.actions;

// Export the reducer function to be used in the Redux store.
export default userSlice.reducer;
