import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// `createApi` is a function from Redux Toolkit Query that allows us to define API endpoints and how they interact with our application.
// `fetchBaseQuery` is a built-in function that provides a base implementation for making HTTP requests.

export const userApi = createApi({
  reducerPath: 'userApi', 
  // `reducerPath` is the unique key in the Redux store where this API's reducer will be placed.

  baseQuery: fetchBaseQuery({ baseUrl: process.env.REACT_APP_API_BASE_URL }), 
  // `baseQuery` defines the base URL for all API requests. It uses an environment variable for flexibility between different environments (development, production, etc.).

  endpoints: (builder) => ({
    // `endpoints` defines all the API operations (queries and mutations) related to users.

    fetchUsers: builder.query({
      // A query to fetch all users from the `/api/users` endpoint.
      query: () => '/api/users',
    }),

    loadAllowedPages: builder.query({
     
      query: () => '/api/allowed-Pages',
    }),

    loadAllowedActions: builder.query({

      query: () => '/api/allowed-Actions',
    }),

    createUser: builder.mutation({
      // A mutation to create a new user. Mutations are used when we want to send data that changes the state on the server.
      query: (newUser) => ({
        url: '/api/users', // Endpoint URL for user creation.
        method: 'POST', // HTTP method to send the request.
        body: newUser, // The body of the request contains the new user data to be sent.
      }),
    }),

    updateUser: builder.mutation({
      // A mutation to update an existing user.
      query: ({ id, ...updatedUser }) => ({
        url: `/api/users/${id}`, // Endpoint URL for updating the user, which includes the user's ID.
        method: 'PUT', // HTTP method to send the request.
        body: updatedUser, // The body of the request contains the updated user data.
      }),
    }),

    deleteUser: builder.mutation({
      // A mutation to delete a user.
      query: (id) => ({
        url: `/api/users/${id}`, // Endpoint URL for deleting the user by their ID.
        method: 'DELETE', // HTTP method to send the request.
      }),
    }),
  }),
});

export const {
  useFetchUsersQuery, // Hook to fetch the list of users.
  useLoadAllowedPagesQuery, // Hook to load allowed pages.
  useLoadAllowedActionsQuery, // Hook to load allowed actions.
  useCreateUserMutation, // Hook to create a new user (used in forms or similar components).
  useUpdateUserMutation, // Hook to update an existing user (used when editing a user).
  useDeleteUserMutation, // Hook to delete a user (used in delete operations).
} = userApi; 
// Exporting all hooks generated by the `userApi` for usage in components.
